image: docker:latest

services:
- docker:dind

before_script:
- ip a s
- apk add --update python py-pip python-dev && pip install docker-compose # install docker-compose
- docker version
- docker-compose version

build-proxy:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - cd proxy
    - docker build --pull -t "$CI_REGISTRY_IMAGE/proxy:$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY_IMAGE/proxy:$CI_COMMIT_TAG"
  only:
    - master

build-web:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - cd web
    - docker build --pull -t "$CI_REGISTRY_IMAGE/web:$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY_IMAGE/web:$CI_COMMIT_TAG"
  only:
    - master

test-build:
  stage: test
  script:
  - mkdir proxy/ssl
  - touch proxy/ssl/apache.key
  - touch proxy/ssl/apache.crt
  - docker-compose build
