image: docker:latest

services:
- docker:dind

before_script:
- ip a s
- apk add --update python py-pip python-dev && pip install docker-compose # install docker-compose
- docker version
- docker-compose version
- docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-proxy:
  stage: build
  script:
#    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - cd proxy
    - docker build --pull -t "$CI_REGISTRY_IMAGE/proxy" .
    - docker push "$CI_REGISTRY_IMAGE/proxy"
  only:
    - master

build-web:
  stage: build
  script:
 #   - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - cd web
    - docker build --pull -t "$CI_REGISTRY_IMAGE/web" .
    - docker push "$CI_REGISTRY_IMAGE/web"
  only:
    - master
    
build-tags:
  stage: build
  script:
#    - export DOCKER_CONTENT_TRUST=1
    - cd web
    - docker build --pull -t "$CI_REGISTRY_IMAGE/web:$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY_IMAGE/web:$CI_COMMIT_TAG"
    - cd ../proxy
    - docker build --pull -t "$CI_REGISTRY_IMAGE/proxy:$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY_IMAGE/proxy:$CI_COMMIT_TAG"
  only:
    - tags

test-build:
  stage: test
  script:
  - docker-compose build
