image: docker:latest

services:
- docker:dind

before_script:
- apk add --update python py-pip python-dev && pip install docker-compose # install docker-compose
- docker version
- docker-compose version
- mkdir proxy/ssl

test-build:
  stage: test
  script:
  - touch proxy/ssl/apache.key
  - touch proxy/ssl/apache.crt
  - docker-compose build

build-proxy:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - cd proxy
    - docker build --pull -t "$CI_REGISTRY_IMAGE/proxy" .
    - docker push "$CI_REGISTRY_IMAGE/proxy"
  only:
    - master
