version: '3'


services:
  proxy:
    container_name: proxy
    restart: always
    env_file:
      - .env
#    build:
#      context: ./proxy
    image: "registry.gitlab.ics.muni.cz:443/europdx/las/las-docker-edirex/proxy:${TAG}"
    volumes:
      - ./proxy/ssl:/usr/local/apache2/conf/ssl
    ports:
      - "8085:8085"
    links:
      - lasneo4j:lasneo4j
      - lasphpmyadmin:lasphpmyadmin

  portainer:
    container_name: portainer
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock --no-auth
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
